import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AuthButton from './components/AuthButton'

// 根版面配置：包含頂部、內容與底部
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen flex flex-col`}
      >
        {/* HEADER：頂部導覽列 */}
        <header className="w-full flex justify-center border-b border-b-foreground/10 h-16">
          <div className="w-full max-w-4xl flex justify-between items-center p-3 text-sm">
            <AuthButton />
          </div>
        </header>
        {/* BODY：主要內容區塊 */}
        <main className="flex-grow flex flex-col items-center">
          {children}
        </main>
        {/* FOOTER：頁尾資訊 */}
        <footer className="w-full flex justify-center border-t border-t-foreground/10 h-16">
          <div className="w-full max-w-4xl flex justify-center items-center p-3 text-sm">
            {/* 這裡可放置版權等資訊 */}
            © 2024 Secure Voting System
          </div>
        </footer>
      </body>
    </html>
  );
}
